#!/usr/bin/env bash -e

OBS=$1
if [ -z $OBS ]; then
  echo "Usage: build bacon|lonna">/dev/stderr
  exit 1
fi

if [ ! -d src/$OBS ]; then
  echo "Observable impl not found: " $OBS >/dev/stderr
  exit 1
fi

rm -fr dist
scripts/switch-observables $OBS

yarn tsc
yarn test

scripts/switch-observables lonna
