#!/usr/bin/env bash
set -euo pipefail

function json_replace() {
    FILE=$1
    FIELD=$2
    VALUE=$3
    perl -pi -e 's/("'$FIELD'".*:.*)".*"/\1"'$VALUE'"/' $FILE
}

OBS=$1 
echo Switching to $OBS observables

git checkout tsconfig.build.json src/observable
perl -pi -e 's/lonna/'$OBS'/' src/observable/*

json_replace tsconfig.build.json outDir $OBS
